version: "3.2"
services:
  web:
    build: .
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - .:/var/www/html
  db:
    image: mysql:8
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db_data/:/var/lib/mysql
