name: Deploy prod
run-name: deploy prod
on:
  release:
    types:
      - created
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Feature prod deploy..."